apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deploy
  namespace: aws9h
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      initContainers:
      - name: copy-index
        image: hub.aws9.pri/library/news-nginx:v1  # index.html 포함된 이미지
        command: ["/bin/sh", "-c"]
        args:
          - cp /usr/share/nginx/html/index.html /mnt/index.html
        volumeMounts:
        - name: news-volume
          mountPath: /mnt
      containers:
      - name: news-container
        image: hub.aws9.pri/library/news-nginx:v1 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: news-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: news-volume
        persistentVolumeClaim:
          claimName: news-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
  namespace: aws9h
spec:
  selector:
    app: news
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-pvc
  namespace: aws9h
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws9h-storage

