apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
  namespace: aws9h
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: blog
  template:
    metadata:
      labels:
        tag: blog
    spec:
      initContainers:
      - name: copy-index
        image: hub.aws9.pri/library/shop-nginx:v1  # index.html 포함된 이미지
        command: ["/bin/sh", "-c"]
        args:
          - cp /usr/share/nginx/html/index.html /mnt/index.html
        volumeMounts:
        - name: blog-volume
          mountPath: /mnt
      containers:
        - name: blog-container
          image: hub.aws9.pri/library/blog-nginx:v1 
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: blog-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: blog-volume
          persistentVolumeClaim:
            claimName: blog-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: aws9h
spec:
  selector:
    tag: blog
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-pvc
  namespace: aws9h
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: aws9h-storage